### ISSUE TITLE
Should the bindings be locked to a thread when executing libvirt commands?

### ISSUE THREAD

**Issue by rmohr** [libvirt/libvirt-go#38]
I wonder if the library has to use [LockOSThread](https://golang.org/pkg/runtime/#LockOSThread) when calling the c-bindings.

In kubevirt we repeatedly see libvirt errors like `virError(Code=0, Domain=0, Message='Missing error'`. It looks like they may happen when between the actual libvirt call and fetching the libvirt error with `GetLastError()`, goroutine switches happen. I have the suspicion because `GetLastError` retrieves the error from a thread-local location.

**Comment by berrange** [comment]
Yes, you are correct - virGetLastError *is* fetching from a thread local variable inside libvirt. So the native thread running the GetLastError call must be the same as the native thread that ran the API that failed

**Comment by berrange** [comment]
Fun, 480+  locations of this bug. I'll put this on my to do list to fix as a top priority item.

**Comment by berrange** [comment]
Urgh, until Go 1.9,  LockOSThread calls are not reference counted, so no matter how many times you call LockOSThread, the first UnlockOSThread unlocks it:

commit c85b12b5796c7efd4d8311253208b47449161361
Author: Austin Clements <austin@google.com>
Date:   Wed Jun 14 11:46:35 2017 -0400

    runtime: make LockOSThread/UnlockOSThread nested
    
    Currently, there is a single bit for LockOSThread, so two calls to
    LockOSThread followed by one call to UnlockOSThread will unlock the
    thread. There's evidence (#20458) that this is almost never what
    people want or expect and it makes these APIs very hard to use
    correctly or reliably.
    
    Change this so LockOSThread/UnlockOSThread can be nested and the
    calling goroutine will not be unwired until UnlockOSThread has been
    called as many times as LockOSThread has. This should fix the vast
    majority of incorrect uses while having no effect on the vast majority
    of correct uses.
    
    Fixes #20458.
    
    Change-Id: I1464e5e9a0ea4208fbb83638ee9847f929a2bacb
    Reviewed-on: https://go-review.googlesource.com/45752
    Run-TryBot: Austin Clements <austin@google.com>
    TryBot-Result: Gobot Gobot <gobot@golang.org>
    Reviewed-by: Keith Randall <khr@golang.org>

So if libvirt calls LockOSThread + UnlockOSThread inside its APIs, and the application has also called LockOSThread for its own different reasons, we'd be undoing whatever the application has done.

So I see three options

 1. Libvirt calls LockOSThread / UnlockOSThread and simply document that you must use Go 1.9 or later, if the application also intends to use LockOSThread itself

 2. Libvirt calls LockOSThread/UnlockOSThread, but only when using Go >= 1.9. Applications running older Go versions would have to call LockOSThread themselves to get correct error reporting.

 3. No change. All applications would have to call LOckOSThread themselves to get correct error reporting

I'm inclined to go for option 1, since that optimizes for modern Go runtime versions, while options 2/3 optimize for old runtime versions which will be increasingly rarely used.

Any dissenting opinion, or alternative suggestion before we take that route ?

**Comment by berrange** [comment]
Opps, new behaviour is Go >= 1.10, not 1.9

**Comment by berrange** [comment]
Yes, that's right - any native API from Go will block the native thread for the duration of its execution, even without the LockOSThread calls.  I'm a little fuzzy on the implications of that though.  eg the docs say:

  "The GOMAXPROCS variable limits the number of operating system threads that can execute user-level Go code simultaneously. There is no limit to the number of threads that can be blocked in system calls on behalf of Go code;"

its unclear from reading that whether a native thread blocked in a CGo call will count against GOMAXPROCS or not.

**Comment by berrange** [comment]
According to the comments at top of https://github.com/golang/go/blob/master/src/runtime/cgocall.go

The threads blocked in cgo calls would not count against GOMAXPROCS limit, as tjhey're treated as being a systemcall from accounting POV

**Comment by rmohr** [comment]
Interesting. So if I understand that correctly, with the LockOSTrhead the behaviour would be different to what we have right now for long running blocked calls, since although it does something which is treated as a system call, it will still block the thread because of the lock. But since go should just spawn new threads anyway it should not be an issue.

**Comment by berrange** [comment]
I think LockOSThread should still be OK, as we'll initially lock the thread which would count against GOMAXPROCS, but when we then call into the cgo code IIUC the thread will temporarily stop being counted against GOMAXPROCS until cgo completes.

This all said, I'm now thinking about an alternative solution which avoids LockOSThread. In order todo conditional compilation for any APIs added since libvirt 1.2.0, we're defining C wrappers. eg instead of calling C.virDomainFoo, we call C.virDomainFooCompat which then calls virDomainFoo. We could perhaps make use of the Compat functions to capture the error information at the C level where we're still guaranteed to be serialized and then pass it back upto go. It is more coding code, but I think it might be a nicer solution overall.

**Comment by rmohr** [comment]
The wrapper solution sounds like it's more future proof. That sounds great.

**Comment by berrange** [comment]
I've implemented the new error reporting strategy and it passes our basic tests. It is quite a large refactoring though, so I'd appreciate if you can do some tests against it with KubeVirt to validate it solves the issues you saw, before I push it to git master. 

The patches are on this branch:

https://github.com/berrange/libvirt-go/tree/thread-safe-errors

**Comment by cynepco3hahue** [comment]
@berrange Runs look good, no missing errors.

**Comment by rmohr** [comment]
Triggered it too on our PR and locally a few times more. No "missing error" or other new issues seem to pop up. So looks good.

**Comment by berrange** [comment]
This is now pushed to git master

**Comment by cynepco3hahue** [comment]
@berrange Hi Daniel, do you know how often GitHub libvirt-go repository does a sync with http://libvirt.org/git/?p=libvirt-go.git;a=summary, we want to start using a fix, but I can not see the latest changes under the GitHub repository.
