### ISSUE TITLE
Accessing Connect.IsAlive()'s error segfaults

### ISSUE THREAD

**Issue by ifoo** [libvirt/libvirt-go#44]
When checking if the connection to libvirt is alive with `func (*Connect) IsAlive` if libvirtd was stopped after opening the connection, accessing the returned `error` segfaults the application.

Example: https://play.golang.org/p/Yhh9bHcuwkh

Output: 

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4c39da]

goroutine 1 [running]:
main.main()
        /path/main.go:23 +0x9a
exit status 2
```

Calling `IsAlive()` works fine, but accessing the returned error segfaults.

**Comment by berrange** [comment]
Accessing the error segfaults because the error is nil in your case

	fmt.Printf("alive: %t, err: %s", alive, err.Error())

Somewhat unhelpfully, the 'IsAlive' method will only update its view of liveliness if you've called some API, or have an event loop impl registered to allow it to be updated asynchronously.

So in your example, it is in fact returning 'true, nil'.

Change your example to

	conn.GetHostname()
	alive, err := conn.IsAlive()
	fmt.Printf("alive: %t\n", alive)
	fmt.Printf("err: %t\n", err)

and you'll see it work correctly.
