### ISSUE TITLE
Sync documentation to godoc?

### ISSUE THREAD

**Issue by purpleidea** [libvirt/libvirt-go#6]
The bindings are working great, thank you!

However, the documentation in godoc is difficult to use because the helpful descriptions aren't in there, but in here: https://libvirt.org/html/libvirt-libvirt-domain.html (for example). Is there a way to either sync those docs to the bindings, or to at least provide a link to the correct spots in the upstream C API docs?

Automation would be great, but if we should be sending patches, LMK.

**Comment by berrange** [comment]
I don't think we want to sync the docs across because concepts in the C docs don't match concepts in the Go APIs directly in many cases - in particular in any API with typed parameters.

We could add a hyperlink to the C API docs against each Go API. eg

"For further information on the underlying C see https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetInfo"

or something like that. We could probably write a script to automatically add this message for all existing APIs and then just commit the result.

**Comment by berrange** [comment]
We now link to the C lib docs

commit 0822ea6d658d7a0deeaa2ce63ed3efd6306bee03 (HEAD -> master)
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Fri Sep 1 15:31:55 2017 +0100

    Generate links to C library API docs

**Comment by purpleidea** [comment]
@berrange Whoa, really awesome!

Did someone write a one-shot script or was this a manual process?

Thanks!

**Comment by berrange** [comment]
It was a horrible perl script that I'm throwing away
